#!/usr/bin/env python
"""
Convert from and to HDF5
"""

import sys, os, getopt
import ml2h5.converter
from ml2h5.converter import TO_H5,FROM_H5
from optparse import OptionParser



def oParse():
    parser=OptionParser()
    parser.add_option('-s','--seperator',dest='seperator',help='',default=None)
    parser.add_option('-v', '--verify',action='store_true',dest='verify',help='',default=False)
    parser.add_option('-f', '--first-line-attribute-names',action='store_true',dest='attribute_names_first',help='',default=False)
    parser.add_option('-i', '--format-in',dest='format_in',help='',default=None)
    parser.add_option('-o', '--format-out',dest='format_out',help='',default=None)
    parser.add_option('-m', '--merge-data',action='store_true',dest='merge',help='',default=False)
    parser.add_option('-n', '--no-conversion',action='store_false',dest='convert',help='',default=True)
    
    return parser.parse_args()


def usage():
    msg = [ml2h5.PROGRAM_NAME + ', Version ' + ml2h5.VERSION + """

Usage: """ + sys.argv[0] + """ [options] <in-filename> <out-filename>

Options:

-s, --seperator
    Seperator to use to seperate variables in examples. Default is ','

-v, --verfiy
    Verify the converted data

-f, --first-line-attribute-names
    First line contains attributes names (for CSV)

-i, --format-in
    File format of in-file (if auto-detection fails)

-o, --format-out
    File format of out-file (if auto-detection fails)

    Supported conversions are:
"""]

    for item in TO_H5:
        msg.append('    ' + item + ' -> ' + 'h5')
    msg.append('')
    for item in FROM_H5:
        msg.append('    h5 -> ' + item)

    print "\n".join(msg)


class Options:
    """Option.

    Should not be instantiated.

    @cvar seperator: seperator to seperate variables in examples
    @type output: string
    @cvar verify: if converted data shall be verified against input data
    @type verify: boolean
    @cvar attribute_names_first: if first line in CSV files shall be treated as attribute names
    @type attribute_names_first: boolean
    @cvar format_in: file format of in-file
    @type format_in: string
    @cvar format_out: file format of out-file
    @type format_out: string
    """
    seperator = None
    verify = False
    attribute_names_first = False
    format_in = None
    format_out = None
    merge = False


def rm_opt(option, value=None):
    """Remove given option and value from sys.argv.

    @param option: option to remove
    @type option: string
    @param value: value to remove
    @type value: string
    """
    if not value:
        sys.argv.remove(option)
        return

    try:
        sys.argv.remove(option + value)
    except ValueError:
        try:
            sys.argv.remove(option)
            sys.argv.remove(value)
        except ValueError:
            sys.argv.remove(option + '=' + value)


def parse_options():
    """Parse given options."""
    try:
        opts, args = getopt.getopt(sys.argv[1:], 's:vfcim:o:',
            ['seperator=', 'verify', 'first-line-attribute-names',
                'compression', 'merge', 'format-in=', 'format-out='])
    except getopt.GetoptError, err: # print help information and exit
        print str(err) + "\n"
        usage()
        sys.exit(1)

    for o, a in opts:
        if o in ('-s', '--seperator'):
            Options.seperator = a
        elif o in ('-v', '--verify'):
            Options.verify = True
        elif o in ('-f', '--first-line-attribute-names'):
            Options.attribute_names_first = True
        elif o in ('-i', '--format-in'):
            Options.format_in = a
        elif o in ('-o', '--format-out'):
            Options.format_out = a
        elif o in ('-m', '--merge-data'):
            Options.merge = True
        else:
            print 'Unhandled option: ' + o
            sys.exit(2)
        rm_opt(o, a)


if __name__ == "__main__":
#    parse_options()
    (Options,args)=oParse()
    argc = len(sys.argv)
    if  argc < 3:
        usage()
        sys.exit(1)

#    if sys.argv[2] == 'h5':
    if args[1] == 'h5':
        seperator = None
    elif Options.seperator:
        seperator = Options.seperator
    else:
#        seperator = ml2h5.fileformat.infer_seperator(sys.argv[1])
        seperator = ml2h5.fileformat.infer_seperator(args[0])
    c = ml2h5.converter.Converter(
#        sys.argv[1], sys.argv[2],
        args[0], args[1],
        format_in=Options.format_in, format_out=Options.format_out,
        seperator=seperator,
        attribute_names_first=Options.attribute_names_first,
        merge=Options.merge
    )
    if Options.convert:
        c.run(verify=Options.verify)
    if Options.verify:
        c.verify()    
