#!/usr/bin/env python
"""
Print an extract of an HDF5 file, similar to website output
"""

import sys
import ml2h5.data

def usage():
    print("""Usage: """ + sys.argv[0] + """ <filename>""")


if __name__ == "__main__":
    argc = len(sys.argv)
    if  argc < 2:
        usage()
        sys.exit(1)

    print(ml2h5.data.get_extract(sys.argv[1]))
